# Generated by Django 4.2.7 on 2023-11-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idade',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='usuario',
        ),
    ]
